### ISSUE TITLE
Invalid Template Name

### ISSUE THREAD

**Issue by akncnkoc** [knowankit/build-react-npm#35]
hi, cli seems broken right now

<img width="1500" src="https://i.imgur.com/E7MEByM.png">

can you fix ? @knowankit

**Comment by knowankit** [comment]
@akncnkoc Thank you for raising this issue. I am on it.

**Comment by knowankit** [comment]
@akncnkoc Giving name to the template is not supported yet. You can create a folder and name it and get into the folder and run `build-react-npm` and you can directly change the name from the package.json for now.

I will support this in the next release.

<img width="425" alt="Screenshot 2022-04-12 at 6 46 51 AM" src="https://user-images.githubusercontent.com/44323532/162859199-cb584b36-6110-4e13-88ec-e7641fdd1830.png">
